---
title: 
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Getting and Cleaning Data: Course Project

## Introduction

This repository contains files relevant for the course project for the Coursera course "Getting and Cleaning data". The Human Activity Recognition Using Smartphones Dataset was used for the purpose of this assignment.

The repository contains the following a complete reproducible R code for the assignment, the code book explaining in details the experiment performed with the amsung Galaxy S II by Jorge L. Reyes-Ortiz and co-workers, and the resulted tidy dataset.

## Assignment purpose
For the purpose of this assignment the R script called run_analysis was created. The R code does the following:
1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

## Reference
Use of this dataset in publications must be acknowledged by referencing the following publication:
1. Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.